-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.paciente
(
    id bigint,
    nome text NOT NULL,
    foto bytea,
    cpf character(14)[] NOT NULL,
    rg character(12)[] NOT NULL,
    nascimento date,
    email text NOT NULL,
    contato_id bigint,
    PRIMARY KEY (id),
    CONSTRAINT unique_contato UNIQUE (contato_id)
);

CREATE TABLE IF NOT EXISTS public.contato
(
    id bigint NOT NULL,
    nome text NOT NULL,
    telefone character(45)[] NOT NULL,
    email text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exame
(
    id bigint,
    nome text,
    resultado text,
    medico_id bigint,
    paciente_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medico
(
    id bigint,
    nome text NOT NULL,
    crm character(13)[] NOT NULL,
    especialidade text NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_crm UNIQUE (crm)
);

CREATE TABLE IF NOT EXISTS public.imagem
(
    id bigint,
    arquivo bytea,
    exame_id bigint,
    laudo text,
    CONSTRAINT unique_exame PRIMARY KEY (exame_id, id)
);

CREATE TABLE IF NOT EXISTS public.doenca
(
    id bigint,
    nome text,
    descricao text,
    sintomas text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doenca_paciente
(
    doenca_id bigint,
    paciente_id bigint,
    data_descoberta date,
    PRIMARY KEY (doenca_id, paciente_id)
);

ALTER TABLE IF EXISTS public.paciente
    ADD FOREIGN KEY (contato_id)
    REFERENCES public.contato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.exame
    ADD FOREIGN KEY (paciente_id)
    REFERENCES public.paciente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.exame
    ADD FOREIGN KEY (medico_id)
    REFERENCES public.medico (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.imagem
    ADD FOREIGN KEY (exame_id)
    REFERENCES public.exame (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.doenca_paciente
    ADD FOREIGN KEY (doenca_id)
    REFERENCES public.doenca (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.doenca_paciente
    ADD FOREIGN KEY (paciente_id)
    REFERENCES public.paciente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;