-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 23:40:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mmmf17-tcc-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mmmf17-tcc-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mmmf17-tcc-db` DEFAULT CHARACTER SET utf8 ;
USE `mmmf17-tcc-db` ;

-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`medico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `crm` VARCHAR(13) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`contato` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`paciente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `foto` LONGBLOB NULL,
  `cpf` VARCHAR(14) NULL,
  `rg` VARCHAR(12) NULL,
  `nascimento` DATE NULL,
  `email` VARCHAR(45) NULL,
  `contato_id` INT NOT NULL,
  `contato_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `contato_id`),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `nascimento_UNIQUE` (`nascimento` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_paciente_contato1_idx` (`contato_id1` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_contato1`
    FOREIGN KEY (`contato_id1`)
    REFERENCES `mmmf17-tcc-db`.`contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`exame` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `resultado` MEDIUMTEXT NULL,
  `data` DATE NULL,
  `examecol` VARCHAR(45) NULL,
  `medico_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `` INT NOT NULL,
  PRIMARY KEY (`id`, `medico_id`, `paciente_id`, ``),
  INDEX `fk_exame_medico1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_exame_paciente1_idx` (`paciente_id` ASC, `` ASC) VISIBLE,
  CONSTRAINT `fk_exame_medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `mmmf17-tcc-db`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exame_paciente1`
    FOREIGN KEY (`paciente_id` , ``)
    REFERENCES `mmmf17-tcc-db`.`paciente` (`id` , `contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`imagem` (
  `id` INT NOT NULL,
  `imagenscol` VARCHAR(45) NULL,
  `arquivo` LONGBLOB NULL,
  `exame_id` INT NOT NULL,
  `exame_medico_id` INT NOT NULL,
  `exame_paciente_id` INT NOT NULL,
  `exame_` INT NOT NULL,
  PRIMARY KEY (`id`, `exame_id`, `exame_medico_id`, `exame_paciente_id`, `exame_`),
  INDEX `fk_imagem_exame1_idx` (`exame_id` ASC, `exame_medico_id` ASC, `exame_paciente_id` ASC, `exame_` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_exame1`
    FOREIGN KEY (`exame_id` , `exame_medico_id` , `exame_paciente_id` , `exame_`)
    REFERENCES `mmmf17-tcc-db`.`exame` (`id` , `medico_id` , `paciente_id` , ``)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`doenca` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `sintomas` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mmmf17-tcc-db`.`doenca_has_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mmmf17-tcc-db`.`doenca_has_paciente` (
  `doenca_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `data_descoberta` DATE NOT NULL,
  PRIMARY KEY (`doenca_id`, `paciente_id`, `data_descoberta`),
  INDEX `fk_doenca_has_paciente_paciente1_idx` (`paciente_id` ASC, `data_descoberta` ASC) VISIBLE,
  INDEX `fk_doenca_has_paciente_doenca1_idx` (`doenca_id` ASC) VISIBLE,
  CONSTRAINT `fk_doenca_has_paciente_doenca1`
    FOREIGN KEY (`doenca_id`)
    REFERENCES `mmmf17-tcc-db`.`doenca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doenca_has_paciente_paciente1`
    FOREIGN KEY (`paciente_id` , `data_descoberta`)
    REFERENCES `mmmf17-tcc-db`.`paciente` (`id` , `contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
